[theme]
primaryColor = "#8000ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
runOnSave = true

[client]
showSidebarNavigation = true
